# ─────────────────────────────────────────────
#  Regression Model – Configuration
# ─────────────────────────────────────────────

data:
  files:
    - "C:/Users/matte/Desktop/NPlus/Git/termocompensazione/data/csv_est/*.parquet"
    - "C:/Users/matte/Desktop/NPlus/Git/termocompensazione/data/csv_incl/*.parquet"
    - "C:/Users/matte/Desktop/NPlus/Git/termocompensazione/data/csv_spost/*.parquet"
    - "C:/Users/matte/Desktop/NPlus/Git/termocompensazione/data/csv_temp/*.parquet"

  time_column: "time"
  tmp_suffix: "_t"
  exclude_columns:
    - "dt"
    - "time"
    - "month"
    - "hour"
    - "datetime"

debug_mode: true

algorithms:
  multiple_linear_regression: true

model:
  lag_time: "15min"
  max_lag: "24h"

output:
  show_plots: false
  save_plots: true
  plot_dir: "output/plots"
